version: '3.7'

services:
    chroma:
        image: chromadb/chroma:latest
        restart: always
        volumes:
          - chroma_data:/chroma/data
        ports:
          - 8000:8000
        # environment:
        #     - CHROMA_SERVER_AUTHN_CREDENTIALS="test-token"
        #     - CHROMA_SERVER_AUTHN_PROVIDER="chromadb.auth.token_authn.TokenAuthenticationServerProvider"
        #     - CHROMA_AUTH_TOKEN_TRANSPORT_HEADER="X_CHROMA_TOKEN"
        networks:
            - ragnet
    rag:
        build:
            context: ./src
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - chroma
        ports:
          - 8080:8080
        networks:
            - ragnet

volumes:
  chroma_data:

networks:
  ragnet:
    driver: bridge
    name: ragnet